Fixed AttributeError: 'str' object has no attribute 'master'
`.Combobox(` uses `tkinter` and only `tcl/tk` objects.
A event from a `tcl/tk` only object can't be handled with `tkinter` methodes.
Here, the `event.widget` attribute **is** the `tcl/tk` object identifier which is of type `str`.
Added a condition to onyl process `tkinter.Widget` objects.